server:
  port: 8091
  servlet-path: /
security:
  basic:
    enabled: false
spring:
  datasource:
    jdbcUrl: jdbc:mysql://206.189.41.190:3306/global?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: global
    password: global@2018
    driverClassName: com.mysql.jdbc.Driver
  jersey:
    application-path: /api
  mail:
    host: mail.vnpt-technology.vn
    port: 25
    username: ump@vnpt-technology.vn
    password: Ump@123
tmpDir: /tmp/ump