server:
  port: 8091
  servlet-path: /
security:
  basic:
    enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/global?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    jdbcUrl: jdbc:mysql://localhost:3306/global?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: global
    password: global@2018
    driverClassName: com.mysql.cj.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 3600000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

  jersey:
    application-path: /api
  mail:
    host: mail.vnpt-technology.vn
    port: 25
    username: ump@vnpt-technology.vn
    password: Ump@123
tmpDir: /tmp/ump