server:
  port: 8092
  servlet-path: /
security:
  basic:
    enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/global?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    jdbcUrl: jdbc:mysql://localhost:3306/global?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: global
    password: global@2018
    driverClassName: com.mysql.cj.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 3600000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  jersey:
    application-path: /api